server:
#    'port: 0' means using random port
    port: 0

spring:
    application:
        name: user-service
    zipkin:
        base-url: http://localhost:9411
        enabled: true
    sleuth:
      sampler:
#          발생된 로그를 어느 정도의 빈도로 전달할 것인지/ 전부 전달
          probability: 1.0
    rabbitmq:
        host: 127.0.0.1
        port: 5672
        username: guest
        password: 3010123
    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true
            path: /h2-console
    jpa:
        show-sql: true
#    datasource:
#        driver-class-name: ${spring.datasource.driver-class-name}
#        url: ${spring.datasource.url}
#        username: ${spring.datasource.username}
#        password: ${spring.datasource.password}
    config:
        import: optional:configserver:http://localhost:8888

    cloud:
      config:
          name: config-service, user-service
#    profiles:
#        active: dev


eureka:
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        # eureka 에 등록
        register-with-eureka: true
        # 외부검색 허용
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
        registry-fetch-interval-seconds: 10

greeting:
    message: Welcome to the Simple E-commerce.

#token:
##    ms 단위 (60 X 60 X 24 X 1000 = 86400000 == 하루)
#    expiration_time: 86400000
#    secret: user_jwt

logging:
    level:
        com.example.userservice: DEBUG

management:
  endpoints:
      web:
          exposure:
              include: info, prometheus, metrics, env, busenv, refresh, health, beans, httptrace, busrefresh

